"""
This file contains the basic crud operations required for
the myorders(financial data) module
_id -> primary key of the collection (automatically generated by
mongoDB)
userId -> getFromUserSessions
cartId -> getFromShoppingCart
totalAmount -> getFromShoppingCart
"""

from pymongo import MongoClient
from pprint import pprint
mongo_cluster = ("mongodb://kajal:kajal@cluster0-shard-00-00-pjkz1.mongodb.net:27017,"
                "cluster0-shard-00-01-pjkz1.mongodb.net:27017,"
                "cluster0-shard-00-02-pjkz1.mongodb.net:27017"
                "/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin")

client = MongoClient(mongo_cluster)

#Database name
db = client["bookstore"]

#Collection name
myCart = db["shoppingCart"]


#API call to user database
userDetails = {
               "userName" : "abcde"
              }

def getUserDetails():
    return userDetails

userId = userDetails["userName"]

"""
addToMyOrders: This method adds transaction of orders to the my orders
"""
def addToMyOrders(userId, cartId):
    #dummy details
    #APICallToProductCatalog
    #productDetails = "curl http://localhost:5000/books/"+productId


    #document to insert
    item = {}

    #Check the schema for user database
    item['userId'] = userDetails['userName']

    #check the exact attribute name for the image
    cartId = myCart.insert_one(item).inserted_id
    #print(cartId)
